name: ci-nodejs-workflow
on:
  pull_request:
    branches:
      - dev

jobs:
  check-test-application:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '20.x']
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
      - run: npm ci

      - name: Run tests
      - run: npm run test

      - name: Run build
      - run: npm run build --if-present
      
      - name: Set Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push to docker hub
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest